import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#3a302a",
        "on-error": "#ffffff",
        outline: "#9a9088",
        "tertiary-fixed-dim": "#e8a0a0",
        "on-tertiary-container": "#3a2020",
        "primary-container": "#e08850",
        "on-tertiary-fixed-variant": "#6e3030",
        "tertiary-container": "#d47070",
        "inverse-on-surface": "#faf5ee",
        "secondary-fixed": "#eae2da",
        "tertiary-fixed": "#fce0e0",
        "on-primary-container": "#fbe8d8",
        "surface-container-highest": "#e6e0d6",
        primary: "#c2652a",
        "outline-variant": "#d8d0c8",
        "on-secondary-fixed": "#2a2420",
        "primary-fixed": "#fbe8d8",
        tertiary: "#8c3c3c",
        "surface-dim": "#dcd6cc",
        error: "#c0392b",
        "surface-container-high": "#ece6dc",
        "surface-container-low": "#f6f0e8",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#eae2da",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#3a302a",
        "primary-fixed-dim": "#f0a878",
        "on-background": "#3a302a",
        background: "#faf5ee",
        surface: "#faf5ee",
        "surface-tint": "#c2652a",
        "inverse-primary": "#f0a878",
        "error-container": "#fce4e0",
        "on-primary-fixed-variant": "#8a4518",
        "on-primary": "#ffffff",
        "surface-variant": "#ece6dc",
        "on-secondary-container": "#605850",
        "on-primary-fixed": "#401a08",
        "on-error-container": "#7a1a10",
        "secondary-fixed-dim": "#cec6be",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#2e1515",
        "on-surface-variant": "#605850",
        "surface-container": "#f2ece4",
        secondary: "#78706a",
        "on-secondary-fixed-variant": "#504840",
        "surface-bright": "#faf5ee",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-display)", "serif"],
        display: ["var(--font-display)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
        label: ["var(--font-body)", "sans-serif"],
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(2.5rem)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.7s ease-out forwards",
      },
    },
  },
  plugins: [],
};
export default config;
